services:
  - type: web
    name: attendo-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: attendo-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://atendo-backend.onrender.com 